# Generated by Django 2.1.2 on 2019-02-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('student_card_image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
