# Generated by Django 2.1.2 on 2019-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '注册', 'verbose_name_plural': '注册'},
        ),
    ]
