# Generated by Django 2.1.2 on 2019-01-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收藏',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('goods_price', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(max_length=300, verbose_name='商品描述')),
                ('goods_img1', models.CharField(max_length=100)),
                ('goods_img2', models.CharField(max_length=100, null=True)),
                ('goods_img3', models.CharField(max_length=100, null=True)),
                ('goods_img4', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-c_time'],
            },
        ),
    ]
