# Generated by Django 2.1 on 2018-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(upload_to='./static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
