# Generated by Django 2.1.2 on 2018-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181006_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_image_URL',
        ),
        migrations.AlterField(
            model_name='productimags',
            name='pictures1',
            field=models.ImageField(upload_to='static/productImages'),
        ),
        migrations.AlterField(
            model_name='productimags',
            name='pictures2',
            field=models.ImageField(null=True, upload_to='static/ProductImages'),
        ),
        migrations.AlterField(
            model_name='productimags',
            name='pictures3',
            field=models.ImageField(null=True, upload_to='static/ProductImages'),
        ),
        migrations.AlterField(
            model_name='productimags',
            name='pictures4',
            field=models.ImageField(null=True, upload_to='static/ProductImages'),
        ),
    ]
