# Generated by Django 2.1.2 on 2019-01-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190117_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='username',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
