# Generated by Django 2.1 on 2018-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180820_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(upload_to='static/ProductImages/%Y/%m/%d'),
        ),
    ]
