# Generated by Django 2.1 on 2018-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180820_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('pictures1', models.ImageField(upload_to='static/ProductImages/%Y/%m/%d')),
                ('pictures2', models.ImageField(null=True, upload_to='static/ProductImages/%Y/%m/%d')),
                ('pictures3', models.ImageField(null=True, upload_to='static/ProductImages/%Y/%m/%d')),
                ('pictures4', models.ImageField(null=True, upload_to='static/ProductImages/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ['-c_time'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
    ]
