# Generated by Django 2.1.2 on 2019-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190117_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_img_width_height',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
