# Generated by Django 2.1.2 on 2019-01-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20190117_1518'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', to_field='username')),
            ],
            options={
                'verbose_name': '收藏',
                'ordering': ['-c_time'],
            },
        ),
    ]
