# Generated by Django 2.1.2 on 2019-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-c_time'], 'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
    ]
